spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false